/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yegorov_alexey_elements_api_Elements */

#ifndef _Included_com_yegorov_alexey_elements_api_Elements
#define _Included_com_yegorov_alexey_elements_api_Elements
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yegorov_alexey_elements_api_Elements
 * Method:    initializeAssets
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_yegorov_alexey_elements_api_Elements_initializeAssets
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
