#ifndef _RECONSTRUCT_CONTROLS_H_
#define _RECONSTRUCT_CONTROLS_H_

#define U_MATRIX_MVP_BUTTON_13			"u_matrix_mvp_button_13"
#define U_COLOR_DIFFUSE_BUTTON_21			"u_color_diffuse_button_21"
#define U_COLOR_SPECULAR_BUTTON_27			"u_color_specular_button_27"
#define VERTEX_0_BUTTON_35			"vertex_0_button_35"
#define VERTEX_1_BUTTON_43			"vertex_1_button_43"
#define VERTEX_2_BUTTON_51			"vertex_2_button_51"
#define VERTEX_3_BUTTON_59			"vertex_3_button_59"
#define RESTORE_BUTTON			"restore_button"

#define U_HAS_MAP_DIFFUSE_CHECK_16			"u_has_map_diffuse_check_16"
#define U_HAS_MAP_SPECULAR_CHECK_17			"u_has_map_specular_check_17"

#define U_MATRIX_MVP_PANEL_14			"u_matrix_mvp_panel_14"
#define U_COLOR_DIFFUSE_PANEL_22			"u_color_diffuse_panel_22"
#define U_COLOR_SPECULAR_PANEL_28			"u_color_specular_panel_28"
#define VERTEX_0_PANEL_36			"vertex_0_panel_36"
#define VERTEX_1_PANEL_44			"vertex_1_panel_44"
#define VERTEX_2_PANEL_52			"vertex_2_panel_52"
#define VERTEX_3_PANEL_60			"vertex_3_panel_60"

#define U_MATRIX_MVP_SLIDER_1			0
#define U_MATRIX_MVP_SLIDER_2			1
#define U_MATRIX_MVP_SLIDER_3			2
#define U_MATRIX_MVP_SLIDER_4			3
#define U_MATRIX_MVP_SLIDER_5			4
#define U_MATRIX_MVP_SLIDER_6			5
#define U_MATRIX_MVP_SLIDER_7			6
#define U_MATRIX_MVP_SLIDER_8			7
#define U_MATRIX_MVP_SLIDER_9			8
#define U_MATRIX_MVP_SLIDER_10			9
#define U_MATRIX_MVP_SLIDER_11			10
#define U_MATRIX_MVP_SLIDER_12			11
#define U_COLOR_DIFFUSE_SLIDER_18			12
#define U_COLOR_DIFFUSE_SLIDER_19			13
#define U_COLOR_DIFFUSE_SLIDER_20			14
#define U_COLOR_SPECULAR_SLIDER_24			15
#define U_COLOR_SPECULAR_SLIDER_25			16
#define U_COLOR_SPECULAR_SLIDER_26			17
#define VERTEX_0_SLIDER_30			18
#define VERTEX_0_SLIDER_31			19
#define VERTEX_0_SLIDER_32			20
#define VERTEX_0_SLIDER_33			21
#define VERTEX_0_SLIDER_34			22
#define VERTEX_1_SLIDER_38			23
#define VERTEX_1_SLIDER_39			24
#define VERTEX_1_SLIDER_40			25
#define VERTEX_1_SLIDER_41			26
#define VERTEX_1_SLIDER_42			27
#define VERTEX_2_SLIDER_46			28
#define VERTEX_2_SLIDER_47			29
#define VERTEX_2_SLIDER_48			30
#define VERTEX_2_SLIDER_49			31
#define VERTEX_2_SLIDER_50			32
#define VERTEX_3_SLIDER_54			33
#define VERTEX_3_SLIDER_55			34
#define VERTEX_3_SLIDER_56			35
#define VERTEX_3_SLIDER_57			36
#define VERTEX_3_SLIDER_58			37

#define SLIDER_MODEL_COUNT			38

#define U_MATRIX_MVP_LABEL_1			"u_matrix_mvp_panel_14/u_matrix_mvp_label_1"
#define U_MATRIX_MVP_LABEL_2			"u_matrix_mvp_panel_14/u_matrix_mvp_label_2"
#define U_MATRIX_MVP_LABEL_3			"u_matrix_mvp_panel_14/u_matrix_mvp_label_3"
#define U_MATRIX_MVP_LABEL_4			"u_matrix_mvp_panel_14/u_matrix_mvp_label_4"
#define U_MATRIX_MVP_LABEL_5			"u_matrix_mvp_panel_14/u_matrix_mvp_label_5"
#define U_MATRIX_MVP_LABEL_6			"u_matrix_mvp_panel_14/u_matrix_mvp_label_6"
#define U_MATRIX_MVP_LABEL_7			"u_matrix_mvp_panel_14/u_matrix_mvp_label_7"
#define U_MATRIX_MVP_LABEL_8			"u_matrix_mvp_panel_14/u_matrix_mvp_label_8"
#define U_MATRIX_MVP_LABEL_9			"u_matrix_mvp_panel_14/u_matrix_mvp_label_9"
#define U_MATRIX_MVP_LABEL_10			"u_matrix_mvp_panel_14/u_matrix_mvp_label_10"
#define U_MATRIX_MVP_LABEL_11			"u_matrix_mvp_panel_14/u_matrix_mvp_label_11"
#define U_MATRIX_MVP_LABEL_12			"u_matrix_mvp_panel_14/u_matrix_mvp_label_12"
#define U_MATRIX_MVP_LABEL_15			"u_matrix_mvp_panel_14/u_matrix_mvp_label_15"
#define U_COLOR_DIFFUSE_LABEL_18			"u_color_diffuse_panel_22/u_color_diffuse_label_18"
#define U_COLOR_DIFFUSE_LABEL_19			"u_color_diffuse_panel_22/u_color_diffuse_label_19"
#define U_COLOR_DIFFUSE_LABEL_20			"u_color_diffuse_panel_22/u_color_diffuse_label_20"
#define U_COLOR_DIFFUSE_LABEL_23			"u_color_diffuse_panel_22/u_color_diffuse_label_23"
#define U_COLOR_SPECULAR_LABEL_24			"u_color_specular_panel_28/u_color_specular_label_24"
#define U_COLOR_SPECULAR_LABEL_25			"u_color_specular_panel_28/u_color_specular_label_25"
#define U_COLOR_SPECULAR_LABEL_26			"u_color_specular_panel_28/u_color_specular_label_26"
#define U_COLOR_SPECULAR_LABEL_29			"u_color_specular_panel_28/u_color_specular_label_29"
#define VERTEX_0_LABEL_30			"vertex_0_panel_36/vertex_0_label_30"
#define VERTEX_0_LABEL_31			"vertex_0_panel_36/vertex_0_label_31"
#define VERTEX_0_LABEL_32			"vertex_0_panel_36/vertex_0_label_32"
#define VERTEX_0_LABEL_33			"vertex_0_panel_36/vertex_0_label_33"
#define VERTEX_0_LABEL_34			"vertex_0_panel_36/vertex_0_label_34"
#define VERTEX_0_LABEL_37			"vertex_0_panel_36/vertex_0_label_37"
#define VERTEX_1_LABEL_38			"vertex_1_panel_44/vertex_1_label_38"
#define VERTEX_1_LABEL_39			"vertex_1_panel_44/vertex_1_label_39"
#define VERTEX_1_LABEL_40			"vertex_1_panel_44/vertex_1_label_40"
#define VERTEX_1_LABEL_41			"vertex_1_panel_44/vertex_1_label_41"
#define VERTEX_1_LABEL_42			"vertex_1_panel_44/vertex_1_label_42"
#define VERTEX_1_LABEL_45			"vertex_1_panel_44/vertex_1_label_45"
#define VERTEX_2_LABEL_46			"vertex_2_panel_52/vertex_2_label_46"
#define VERTEX_2_LABEL_47			"vertex_2_panel_52/vertex_2_label_47"
#define VERTEX_2_LABEL_48			"vertex_2_panel_52/vertex_2_label_48"
#define VERTEX_2_LABEL_49			"vertex_2_panel_52/vertex_2_label_49"
#define VERTEX_2_LABEL_50			"vertex_2_panel_52/vertex_2_label_50"
#define VERTEX_2_LABEL_53			"vertex_2_panel_52/vertex_2_label_53"
#define VERTEX_3_LABEL_54			"vertex_3_panel_60/vertex_3_label_54"
#define VERTEX_3_LABEL_55			"vertex_3_panel_60/vertex_3_label_55"
#define VERTEX_3_LABEL_56			"vertex_3_panel_60/vertex_3_label_56"
#define VERTEX_3_LABEL_57			"vertex_3_panel_60/vertex_3_label_57"
#define VERTEX_3_LABEL_58			"vertex_3_panel_60/vertex_3_label_58"
#define VERTEX_3_LABEL_61			"vertex_3_panel_60/vertex_3_label_61"

#endif
